#!/usr/bin/env python3
"""
Run Sobol Sequence Simulations

Step 2 of the Sobol analysis workflow:
- Reads Sobol sequence from data/sobol_sequence_32.npz (generated by generate_sobol_sequence.py)
- Runs 32 Tidy3D simulations for each parameter point
- Saves HDF5 results to data/results/sobol_32/

Next step: Run generate_surrogate_data.py to process results into surrogate model data.
"""

import sys
from pathlib import Path
import numpy as np
import json
from concurrent.futures import ProcessPoolExecutor, as_completed
from typing import Dict, Any
import time

# Add project root to path
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from modules.simulation_setup import SimulationSetup
from modules.simulation_runner import SimulationRunner
from modules.q_factor_analysis import analyze_q_factor


def run_simulation_for_point(point_data: tuple) -> Dict[str, Any]:
    """Run simulation for a single Sobol sequence point.
    
    Args:
        point_data: Tuple of (point_id, width_um, radius_um, thickness_um)
        
    Returns:
        Dictionary with simulation results
    """
    point_id, width_um, radius_um, thickness_um = point_data
    
    try:
        # Find the GDS files for this point
        point_dir = REPO_ROOT / "gds" / "scaled" / f"sobol_{point_id:02d}"
        cavity_gds = point_dir / f"cavity_sobol_{point_id:02d}_w{width_um:.3f}_r{radius_um:.3f}_t{thickness_um:.3f}.gds"
        holes_gds = point_dir / f"holes_sobol_{point_id:02d}_w{width_um:.3f}_r{radius_um:.3f}_t{thickness_um:.3f}.gds"
        
        if not cavity_gds.exists() or not holes_gds.exists():
            return {
                "point_id": point_id,
                "status": "error",
                "error": f"GDS files not found for point {point_id}"
            }
        
        # Create simulation setup
        setup = SimulationSetup(
            thickness_um=thickness_um,
            wavelength_um=0.62,
            cavity_gds=str(cavity_gds),
            holes_gds=str(holes_gds),
            sidewall_angle_deg=15.6
        )
        
        # Create scout simulation
        sim = setup.create_q_scout_simulation(run_time_ps=7.0, min_steps_per_wvl=13)
        
        # Set up results directory
        results_dir = REPO_ROOT / "data" / "results" / "sobol_32"
        results_dir.mkdir(parents=True, exist_ok=True)
        
        # Create results filename
        results_file = results_dir / f"results_sobol_{point_id:02d}_w{width_um:.3f}_r{radius_um:.3f}_t{thickness_um:.3f}.hdf5"
        
        # Run simulation
        runner = SimulationRunner(task_name=f"sobol_{point_id:02d}")
        sim_data = runner.run_simulation(
            sim, 
            results_path=str(results_file),
            task_name=f"sobol_{point_id:02d}",
            force_rerun=False,
            auto_confirm=True,
            verbose=False  # Disable verbose to avoid Rich conflicts in parallel
        )
        
        if sim_data is None:
            return {
                "point_id": point_id,
                "status": "error",
                "error": "Simulation failed to run"
            }
        
        # Analyze Q-factor
        q_results = analyze_q_factor(
            data_path=str(results_file),
            wavelength_um=0.62,
            save_results=True,
            do_plot=False  # Disable plotting in parallel
        )
        
        return {
            "point_id": point_id,
            "width_um": width_um,
            "radius_um": radius_um,
            "thickness_um": thickness_um,
            "results_file": str(results_file),
            "q_factors": q_results.get("q_factors", []),
            "frequencies_hz": q_results.get("frequencies_hz", []),
            "status": "success"
        }
        
    except Exception as e:
        return {
            "point_id": point_id,
            "status": "error",
            "error": str(e)
        }


def main() -> None:
    """Run all 32 Sobol sequence simulations."""
    print("🚀 Running 32 Sobol sequence simulations...")
    print("=" * 60)
    
    # Load Sobol sequence data
    data_path = REPO_ROOT / "data" / "sobol_sequence_32.npz"
    if not data_path.exists():
        print(f"❌ Error: Sobol sequence data not found at {data_path}")
        return
    
    data = np.load(data_path)
    actual_values = data['actual_values']
    
    # Prepare point data for all 32 points
    point_data_list = []
    for i in range(32):
        point_data = (
            i + 1,  # point_id
            actual_values[i, 0],  # width_um
            actual_values[i, 1],  # radius_um
            actual_values[i, 2]   # thickness_um
        )
        point_data_list.append(point_data)
    
    print(f"📊 Total simulations: 32")
    print(f"💰 Estimated cost: 37.608 FlexCredits")
    print(f"⏱️  Expected runtime: ~2-4 hours (depending on queue)")
    print()
    
    # Run simulations in parallel
    start_time = time.time()
    simulation_results = []
    
    print("🔄 Starting parallel simulations...")
    with ProcessPoolExecutor(max_workers=8) as executor:
        future_to_point = {executor.submit(run_simulation_for_point, point_data): point_data[0] 
                          for point_data in point_data_list}
        
        completed = 0
        for future in as_completed(future_to_point):
            point_id = future_to_point[future]
            try:
                result = future.result()
                simulation_results.append(result)
                completed += 1
                
                if result["status"] == "success":
                    q_factors = result.get("q_factors", [])
                    max_q = max(q_factors) if q_factors else 0
                    print(f"✅ Point {point_id:2d}: Simulation completed (Max Q: {max_q:.0f})")
                else:
                    print(f"❌ Point {point_id:2d}: Failed - {result.get('error', 'Unknown error')}")
                
                # Progress update
                elapsed = time.time() - start_time
                print(f"   Progress: {completed}/32 ({completed/32*100:.1f}%) - Elapsed: {elapsed/60:.1f} min")
                
            except Exception as e:
                print(f"❌ Point {point_id:2d}: Exception - {e}")
                simulation_results.append({
                    "point_id": point_id,
                    "status": "error",
                    "error": str(e)
                })
                completed += 1
    
    # Calculate final statistics
    successful_sims = [r for r in simulation_results if r["status"] == "success"]
    failed_sims = [r for r in simulation_results if r["status"] != "success"]
    
    total_time = time.time() - start_time
    
    print("\n" + "=" * 60)
    print("🎯 SIMULATION COMPLETE!")
    print("=" * 60)
    print(f"✅ Successful: {len(successful_sims)}/32")
    print(f"❌ Failed: {len(failed_sims)}/32")
    print(f"⏱️  Total time: {total_time/60:.1f} minutes")
    print(f"📁 Results saved to: data/results/sobol_32/")
    
    if successful_sims:
        # Calculate Q-factor statistics
        all_q_factors = []
        for result in successful_sims:
            all_q_factors.extend(result.get("q_factors", []))
        
        if all_q_factors:
            print(f"📊 Q-factor statistics:")
            print(f"   Max Q: {max(all_q_factors):.0f}")
            print(f"   Min Q: {min(all_q_factors):.0f}")
            print(f"   Mean Q: {np.mean(all_q_factors):.0f}")
            print(f"   Total modes found: {len(all_q_factors)}")
    
    if failed_sims:
        print(f"\n❌ Failed simulations:")
        for result in failed_sims:
            print(f"   Point {result['point_id']}: {result.get('error', 'Unknown error')}")
    
    # Save summary
    summary = {
        "total_points": 32,
        "successful_simulations": len(successful_sims),
        "failed_simulations": len(failed_sims),
        "total_time_minutes": total_time / 60,
        "simulation_results": simulation_results
    }
    
    summary_path = REPO_ROOT / "data" / "sobol_32_simulation_summary.json"
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    
    print(f"\n📄 Summary saved to: {summary_path}")
    print("\n🎉 All simulations completed! Ready for analysis.")


if __name__ == "__main__":
    main()