#!/usr/bin/env python3
"""
Generate Surrogate Model Data

Step 3 of the Sobol analysis workflow:
- Reads HDF5 simulation results from data/results/sobol_32/ (generated by run_sobol_simulations.py)
- Analyzes Q-factors and wavelengths for each simulation
- Creates surrogate model data file: data/results_summaries/surrogate_model_data.json

Next step: Run inverse_monte_carlo_analysis.py for uncertainty analysis.
"""

import sys
import re
import json
from pathlib import Path

import numpy as np

# Add repo root to path
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from modules.q_factor_analysis import analyze_q_factor, ResonanceConfig
import warnings

q_threshold = 100


def parse_dimensions_from_filename(filename: str) -> dict[str, float] | None:
    match = re.search(r'_w([0-9.]+)_r([0-9.]+)_t([0-9.]+)\.hdf5', filename)
    if not match:
        return None
    return {
        "width": float(match.group(1)),
        "radius": float(match.group(2)),
        "thickness": float(match.group(3)),
    }


def collect_entries(results_dir: Path) -> list[dict[str, float]]:
    entries: list[dict[str, float]] = []

    files = sorted(results_dir.glob("results_sobol_*.hdf5"))

    if not files:
        print(f"❌ No result files found in {results_dir}")
        return entries

    print(f"📁 Found {len(files)} result files. Collecting surrogate entries...")

    ResonanceConfig.do_plot = False  # batch mode

    for i, fp in enumerate(files, 1):
        dims = parse_dimensions_from_filename(fp.name)
        if dims is None:
            print(f"⚠️  Skipping {fp.name}: unable to parse dimensions from filename.")
            continue

        print(f"[{i}/{len(files)}] Analyzing {fp.name}...", end=" ", flush=True)
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                res = analyze_q_factor(data_path=str(fp), wavelength_um=0.62, save_results=False)
            q_factors = res.get("q_factors", [])
            frequencies_hz = res.get("frequencies_hz", [])

            if len(q_factors) == 0 or len(frequencies_hz) == 0:
                print("❌ No modes detected.")
                continue

            # Use selected_index to get the highest-Q mode (same as plot_sobol_3d_analysis_good.py)
            selected_index = res.get('selected_index', 0)
            if selected_index >= len(q_factors) or selected_index >= len(frequencies_hz):
                # Fallback: find highest Q mode
                selected_index = int(np.argmax(q_factors))
            
            q_top = q_factors[selected_index]
            freq_hz = frequencies_hz[selected_index]
            wavelength_nm = 2.99792458e17 / freq_hz if freq_hz > 0 else 0

            # Only store if Q is above threshold
            if q_top > q_threshold:
                entries.append(
                    {
                        "width": dims["width"],
                        "radius": dims["radius"],
                        "thickness": dims["thickness"],
                        "q_factor": float(q_top),
                        "wavelength_nm": float(wavelength_nm),
                    }
                )
                print(f"✓ stored highest-Q mode: Q={q_top:.0f}, λ={wavelength_nm:.1f}nm")
            else:
                print(f"❌ Highest-Q mode (Q={q_top:.0f}) below threshold ({q_threshold})")

        except Exception as exc:
            print(f"❌ Error: {exc}")

    return entries


def save_entries(entries: list[dict[str, float]], output_path: Path) -> None:
    if not entries:
        print("⚠️  No entries collected. Nothing to write.")
        return

    params = {"width": [], "radius": [], "thickness": []}
    responses = {"q_factor": [], "wavelength_nm": []}

    for entry in entries:
        params["width"].append(entry["width"])
        params["radius"].append(entry["radius"])
        params["thickness"].append(entry["thickness"])
        responses["q_factor"].append(entry["q_factor"])
        responses["wavelength_nm"].append(entry["wavelength_nm"])

    payload = {"parameters": params, "responses": responses}

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as fh:
        json.dump(payload, fh, indent=2)

    print(f"💾 Surrogate model data written to: {output_path}")


def main():
    results_dir = REPO_ROOT / "data" / "results" / "sobol_32"
    output_path = REPO_ROOT / "data" / "results_summaries" / "surrogate_model_data.json"

    if not results_dir.exists():
        print(f"❌ Results directory not found: {results_dir}")
        return

    entries = collect_entries(results_dir)
    save_entries(entries, output_path)


if __name__ == "__main__":
    main()

