#!/usr/bin/env python3
"""
Inverse Monte Carlo Uncertainty Analysis

Step 4 of the Sobol analysis workflow:
- Reads surrogate model data from data/results_summaries/surrogate_model_data.json
  (generated by generate_surrogate_data.py)
- Inverts the surrogate model to predict thickness distributions
- Takes manufacturing uncertainties in width, radius, and target wavelength as inputs
- Outputs predicted thickness distributions and statistics

This is the main analysis script for understanding manufacturing tolerances.
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib
try:
    if sys.platform == "darwin":
        matplotlib.use("MacOSX")
    else:
        matplotlib.use("TkAgg")
except Exception:
    matplotlib.use("Agg")  # Fallback for headless environments
import matplotlib.pyplot as plt
import json
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from scipy.optimize import minimize_scalar
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Add project root to path
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

class InverseMonteCarloAnalysisV2:
    """Enhanced Inverse Monte Carlo analysis for thickness prediction."""
    
    def __init__(self, data_file=None):
        if data_file is None:
            data_file = REPO_ROOT / "data" / "results_summaries" / "surrogate_model_data.json"
        elif isinstance(data_file, str) and not Path(data_file).is_absolute():
            data_file = REPO_ROOT / "data" / "results_summaries" / data_file
        self.data_file = Path(data_file)
        self.models = None
        self.data = None
        
    def load_data(self):
        """Load the surrogate model data."""
        print("📊 Loading data...")
        
        with open(self.data_file, 'r') as f:
            data = json.load(f)
        
        # Extract parameters and responses
        parameters = data['parameters']
        responses = data['responses']
        
        # Create DataFrame
        self.data = {
            'width': np.array(parameters['width']),
            'radius': np.array(parameters['radius']), 
            'thickness': np.array(parameters['thickness']),
            'q_factor': np.array(responses['q_factor']),
            'wavelength_nm': np.array(responses['wavelength_nm'])
        }
        
        print(f"✅ Loaded {len(self.data['width'])} data points")
        print(f"   Parameter ranges:")
        print(f"     Width: {self.data['width'].min():.3f} - {self.data['width'].max():.3f} μm")
        print(f"     Radius: {self.data['radius'].min():.3f} - {self.data['radius'].max():.3f} μm")
        print(f"     Thickness: {self.data['thickness'].min():.3f} - {self.data['thickness'].max():.3f} μm")
        print(f"   Response ranges:")
        print(f"     Q-factor: {self.data['q_factor'].min():.0f} - {self.data['q_factor'].max():.0f}")
        print(f"     Wavelength: {self.data['wavelength_nm'].min():.1f} - {self.data['wavelength_nm'].max():.1f} nm")
        
        return self.data
    
    def train_inverse_models(self, model_type='linear_interactions'):
        """Train inverse models to predict thickness from (width, radius, wavelength)."""
        print(f"\n🤖 Training inverse surrogate models ({model_type})...")
        
        # Prepare input features: (width, radius, wavelength) → thickness
        X = np.column_stack([
            self.data['width'],
            self.data['radius'], 
            self.data['wavelength_nm']
        ])
        y = self.data['thickness']
        
        # Normalize features
        X_min = X.min(axis=0)
        X_max = X.max(axis=0)
        X_norm = (X - X_min) / (X_max - X_min)
        
        # Standardize
        scaler_X = StandardScaler()
        scaler_y = StandardScaler()
        
        X_scaled = scaler_X.fit_transform(X_norm)
        y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).ravel()
        
        if model_type == 'linear_interactions':
            # Train inverse thickness model (Linear + Interactions)
            print("  Training linear + interactions model...")
            poly_linear = PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)
            poly_linear.fit(X_scaled)
            feature_names = poly_linear.get_feature_names_out(['width', 'radius', 'wavelength'])
            
            # Find indices of pure quadratic terms to exclude
            pure_quad_indices = []
            for i, name in enumerate(feature_names):
                if '^2' in name and ' ' not in name:  # Pure quadratic
                    pure_quad_indices.append(i)
            
            class LinearPlusInteractions:
                def __init__(self, poly, pure_quad_indices):
                    self.poly = poly
                    self.pure_quad_indices = pure_quad_indices
                    self.linear = LinearRegression()
                
                def fit(self, X, y):
                    X_poly = self.poly.transform(X)
                    # Remove pure quadratic terms
                    X_filtered = np.delete(X_poly, self.pure_quad_indices, axis=1)
                    self.linear.fit(X_filtered, y)
                    return self
                
                def predict(self, X):
                    X_poly = self.poly.transform(X)
                    X_filtered = np.delete(X_poly, self.pure_quad_indices, axis=1)
                    return self.linear.predict(X_filtered)
            
            model_thickness = LinearPlusInteractions(poly_linear, pure_quad_indices)
            model_thickness.fit(X_scaled, y_scaled)
            
        elif model_type == 'quadratic':
            # Train full quadratic model
            print("  Training quadratic model...")
            model_thickness = Pipeline([
                ('poly', PolynomialFeatures(degree=2, include_bias=True)),
                ('linear', LinearRegression())
            ])
            model_thickness.fit(X_scaled, y_scaled)
            
        elif model_type == 'random_forest':
            # Train Random Forest model
            print("  Training Random Forest model...")
            model_thickness = RandomForestRegressor(
                n_estimators=100, 
                max_depth=10, 
                random_state=42,
                n_jobs=-1
            )
            model_thickness.fit(X_scaled, y_scaled)
        
        # Train multiple models for ensemble prediction
        print("  Training ensemble models...")
        model_quad = Pipeline([
            ('poly', PolynomialFeatures(degree=2, include_bias=True)),
            ('linear', LinearRegression())
        ])
        model_quad.fit(X_scaled, y_scaled)
        
        model_rf = RandomForestRegressor(
            n_estimators=50, 
            max_depth=8, 
            random_state=42,
            n_jobs=-1
        )
        model_rf.fit(X_scaled, y_scaled)
        
        self.models = {
            'model_thickness': model_thickness,
            'model_quad': model_quad,
            'model_rf': model_rf,
            'scaler_X': scaler_X,
            'scaler_y': scaler_y,
            'X_min': X_min,
            'X_max': X_max,
            'model_type': model_type
        }
        
        # Evaluate model performance
        self._evaluate_model_performance()
        
        print("✅ Inverse models trained successfully!")
        return self.models
    
    def _evaluate_model_performance(self):
        """Evaluate the performance of the trained models."""
        print("  Evaluating model performance...")
        
        # Prepare test data
        X = np.column_stack([
            self.data['width'],
            self.data['radius'], 
            self.data['wavelength_nm']
        ])
        y_true = self.data['thickness']
        
        # Normalize and scale
        X_norm = (X - self.models['X_min']) / (self.models['X_max'] - self.models['X_min'])
        X_scaled = self.models['scaler_X'].transform(X_norm)
        
        # Predict with main model
        y_pred_scaled = self.models['model_thickness'].predict(X_scaled)
        y_pred = self.models['scaler_y'].inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
        
        # Calculate metrics
        mae = np.mean(np.abs(y_true - y_pred))
        rmse = np.sqrt(np.mean((y_true - y_pred)**2))
        r2 = 1 - np.sum((y_true - y_pred)**2) / np.sum((y_true - np.mean(y_true))**2)
        
        print(f"    MAE: {mae:.4f} μm")
        print(f"    RMSE: {rmse:.4f} μm")
        print(f"    R²: {r2:.4f}")
    
    def predict_thickness(self, width, radius, wavelength, use_ensemble=False):
        """Predict thickness for given width, radius, and wavelength."""
        # Prepare input
        X = np.array([[width, radius, wavelength]])
        
        # Normalize
        X_norm = (X - self.models['X_min']) / (self.models['X_max'] - self.models['X_min'])
        X_scaled = self.models['scaler_X'].transform(X_norm)
        
        if use_ensemble:
            # Use ensemble of models
            pred1_scaled = self.models['model_thickness'].predict(X_scaled)
            pred2_scaled = self.models['model_quad'].predict(X_scaled)
            pred3_scaled = self.models['model_rf'].predict(X_scaled)
            
            # Average predictions
            y_scaled_pred = (pred1_scaled + pred2_scaled + pred3_scaled) / 3
        else:
            # Use main model
            y_scaled_pred = self.models['model_thickness'].predict(X_scaled)
        
        # Transform back to original scale
        y_pred = self.models['scaler_y'].inverse_transform(y_scaled_pred.reshape(-1, 1)).ravel()
        
        return y_pred[0]
    
    def run_inverse_monte_carlo_simulation(self, 
                                        width_mean, width_std,
                                        radius_mean, radius_std, 
                                        wavelength_mean, wavelength_std,
                                        n_simulations=10000,
                                        use_ensemble=False,
                                        seed=42):
        """Run inverse Monte Carlo simulation to predict thickness distributions.
        
        Parameters:
        -----------
        width_mean : float
            Mean width in μm
        width_std : float
            Width standard deviation in μm
        radius_mean : float
            Mean radius in μm
        radius_std : float
            Radius standard deviation in μm
        wavelength_mean : float
            Mean wavelength in nm
        wavelength_std : float
            Wavelength standard deviation in nm
        n_simulations : int
            Number of Monte Carlo samples
        use_ensemble : bool
            Whether to use ensemble prediction
        seed : int
            Random seed for reproducibility
        """
        print(f"\n🎲 Running Inverse Monte Carlo simulation with {n_simulations:,} samples...")
        print(f"  Input parameters:")
        print(f"    Width: {width_mean:.3f} ± {width_std:.3f} μm")
        print(f"    Radius: {radius_mean:.3f} ± {radius_std:.3f} μm")
        print(f"    Wavelength: {wavelength_mean:.1f} ± {wavelength_std:.1f} nm")
        print(f"  Ensemble prediction: {'Yes' if use_ensemble else 'No'}")
        
        # Set random seed
        np.random.seed(seed)
        
        # Generate random samples
        width_samples = np.random.normal(width_mean, width_std, n_simulations)
        radius_samples = np.random.normal(radius_mean, radius_std, n_simulations)
        wavelength_samples = np.random.normal(wavelength_mean, wavelength_std, n_simulations)
        
        # Predict thickness for each sample
        thickness_predictions = []
        valid_samples = 0
        invalid_reasons = {'out_of_bounds': 0, 'prediction_error': 0}
        
        print("  Predicting thickness for each sample...")
        for i in range(n_simulations):
            try:
                # Check input bounds
                if not (0.2 <= width_samples[i] <= 0.45 and 
                       0.025 <= radius_samples[i] <= 0.06 and 
                       600 <= wavelength_samples[i] <= 700):
                    thickness_predictions.append(np.nan)
                    invalid_reasons['out_of_bounds'] += 1
                    continue
                
                thickness = self.predict_thickness(
                    width_samples[i], 
                    radius_samples[i], 
                    wavelength_samples[i],
                    use_ensemble=use_ensemble
                )
                
                # Check if prediction is within reasonable bounds
                if 0.05 <= thickness <= 0.25:  # Reasonable thickness range
                    thickness_predictions.append(thickness)
                    valid_samples += 1
                else:
                    thickness_predictions.append(np.nan)
                    invalid_reasons['out_of_bounds'] += 1
                    
            except Exception as e:
                thickness_predictions.append(np.nan)
                invalid_reasons['prediction_error'] += 1
            
            if (i + 1) % 1000 == 0:
                print(f"    Processed {i + 1:,} samples...")
        
        # Filter out invalid predictions
        valid_mask = [not np.isnan(t) for t in thickness_predictions]
        valid_thickness = np.array([t for t in thickness_predictions if not np.isnan(t)])
        
        # Filter input arrays to match valid predictions
        valid_width = width_samples[valid_mask]
        valid_radius = radius_samples[valid_mask]
        valid_wavelength = wavelength_samples[valid_mask]
        
        print(f"✅ Inverse Monte Carlo simulation complete!")
        print(f"  Generated {len(valid_thickness):,} valid thickness predictions")
        print(f"  Success rate: {len(valid_thickness)/n_simulations*100:.1f}%")
        print(f"  Invalid samples: {invalid_reasons}")
        
        return {
            'thickness': valid_thickness,
            'width_samples': valid_width,
            'radius_samples': valid_radius,
            'wavelength_samples': valid_wavelength,
            'n_simulations': n_simulations,
            'valid_samples': len(valid_thickness),
            'invalid_reasons': invalid_reasons
        }
    
    def analyze_thickness_distribution(self, results):
        """Analyze the thickness distribution."""
        print("\n📊 Analyzing thickness distribution...")
        
        thickness = results['thickness']
        
        if len(thickness) == 0:
            print("❌ No valid thickness predictions found!")
            return None
        
        # Calculate statistics
        thickness_stats = {
            'mean': np.mean(thickness),
            'std': np.std(thickness),
            'min': np.min(thickness),
            'max': np.max(thickness),
            'percentile_5': np.percentile(thickness, 5),
            'percentile_25': np.percentile(thickness, 25),
            'percentile_50': np.percentile(thickness, 50),
            'percentile_75': np.percentile(thickness, 75),
            'percentile_95': np.percentile(thickness, 95),
            'cv': np.std(thickness) / np.mean(thickness) * 100,  # coefficient of variation
            'skewness': stats.skew(thickness),
            'kurtosis': stats.kurtosis(thickness)
        }
        
        print(f"Thickness statistics:")
        print(f"  Mean: {thickness_stats['mean']:.3f} μm")
        print(f"  Std: {thickness_stats['std']:.3f} μm")
        print(f"  CV: {thickness_stats['cv']:.1f}%")
        print(f"  Median: {thickness_stats['percentile_50']:.3f} μm")
        print(f"  5th percentile: {thickness_stats['percentile_5']:.3f} μm")
        print(f"  95th percentile: {thickness_stats['percentile_95']:.3f} μm")
        print(f"  Range: {thickness_stats['min']:.3f} - {thickness_stats['max']:.3f} μm")
        print(f"  Skewness: {thickness_stats['skewness']:.3f}")
        print(f"  Kurtosis: {thickness_stats['kurtosis']:.3f}")
        
        # Normality test
        shapiro_stat, shapiro_p = stats.shapiro(thickness)
        print(f"  Shapiro-Wilk normality test: p = {shapiro_p:.3f}")
        
        return thickness_stats
    
    def create_distribution_plots(self, results, thickness_stats, 
                                width_mean, width_std,
                                radius_mean, radius_std,
                                wavelength_mean, wavelength_std):
        """Create plots showing input and output distributions."""
        print("\n📈 Creating distribution plots...")
        
        thickness = results['thickness']
        
        if len(thickness) == 0:
            print("❌ No valid thickness predictions to plot!")
            return None
        
        # Create figure with 2x2 subplots
        fig, axes = plt.subplots(2, 2, figsize=(12, 10))
        fig.suptitle('Inverse Monte Carlo Analysis: Input and Output Distributions', fontsize=14, fontweight='bold')
        
        # 1. Input: Width distribution
        ax1 = axes[0, 0]
        ax1.hist(results['width_samples'], bins=50, alpha=0.7, color='blue', edgecolor='black', density=True)
        ax1.axvline(width_mean, color='red', linestyle='--', linewidth=2, label=f"Mean: {width_mean:.3f} μm")
        ax1.set_xlabel('Width (μm)')
        ax1.set_ylabel('Density')
        ax1.set_title(f'Input: Width Distribution (σ={width_std:.3f} μm)')
        ax1.legend()
        ax1.grid(True, alpha=0.3)
        
        # 2. Input: Radius distribution
        ax2 = axes[0, 1]
        ax2.hist(results['radius_samples'], bins=50, alpha=0.7, color='green', edgecolor='black', density=True)
        ax2.axvline(radius_mean, color='red', linestyle='--', linewidth=2, label=f"Mean: {radius_mean:.3f} μm")
        ax2.set_xlabel('Radius (μm)')
        ax2.set_ylabel('Density')
        ax2.set_title(f'Input: Radius Distribution (σ={radius_std:.3f} μm)')
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        # 3. Input: Wavelength distribution
        ax3 = axes[1, 0]
        ax3.hist(results['wavelength_samples'], bins=50, alpha=0.7, color='red', edgecolor='black', density=True)
        ax3.axvline(wavelength_mean, color='red', linestyle='--', linewidth=2, label=f"Mean: {wavelength_mean:.1f} nm")
        ax3.set_xlabel('Wavelength (nm)')
        ax3.set_ylabel('Density')
        ax3.set_title(f'Input: Wavelength Distribution (σ={wavelength_std:.1f} nm)')
        ax3.legend()
        ax3.grid(True, alpha=0.3)
        
        # 4. Output: Thickness distribution
        ax4 = axes[1, 1]
        ax4.hist(thickness, bins=50, alpha=0.7, color='skyblue', edgecolor='black', density=True)
        ax4.axvline(thickness_stats['mean'], color='red', linestyle='--', linewidth=2, label=f"Mean: {thickness_stats['mean']:.3f} μm")
        ax4.axvline(thickness_stats['percentile_5'], color='orange', linestyle=':', linewidth=2, label=f"5th: {thickness_stats['percentile_5']:.3f} μm")
        ax4.axvline(thickness_stats['percentile_95'], color='orange', linestyle=':', linewidth=2, label=f"95th: {thickness_stats['percentile_95']:.3f} μm")
        ax4.set_xlabel('Thickness (μm)')
        ax4.set_ylabel('Density')
        ax4.set_title(f'Output: Thickness Distribution (σ={thickness_stats["std"]:.3f} μm)')
        ax4.legend()
        ax4.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        # Save plot
        output_file = "figures/inverse_monte_carlo_thickness_analysis_v2.png"
        Path("figures").mkdir(exist_ok=True)
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"💾 Distribution plots saved to: {output_file}")
        
        # Display the plot for interactive inspection
        try:
            plt.show()
        except Exception:
            pass
        
        # Close the figure to prevent memory issues
        plt.close(fig)
        
        return fig
    
    def run_analysis(self, 
                    width_mean, width_std,
                    radius_mean, radius_std,
                    wavelength_mean, wavelength_std,
                    n_simulations=10000,
                    model_type='linear_interactions',
                    use_ensemble=False,
                    seed=42):
        """Run the complete inverse Monte Carlo analysis.
        
        Parameters:
        -----------
        width_mean : float
            Mean width in μm
        width_std : float
            Width standard deviation in μm
        radius_mean : float
            Mean radius in μm
        radius_std : float
            Radius standard deviation in μm
        wavelength_mean : float
            Mean wavelength in nm
        wavelength_std : float
            Wavelength standard deviation in nm
        n_simulations : int
            Number of Monte Carlo samples
        model_type : str
            Type of model to use ('linear_interactions', 'quadratic', 'random_forest')
        use_ensemble : bool
            Whether to use ensemble prediction
        seed : int
            Random seed for reproducibility
        """
        print("🎲 Inverse Monte Carlo Uncertainty Analysis v2 for Photonic Cavity Manufacturing")
        print("=" * 80)
        
        # Load data and train models
        self.load_data()
        self.train_inverse_models(model_type=model_type)
        
        # Run Monte Carlo simulation
        results = self.run_inverse_monte_carlo_simulation(
            width_mean=width_mean,
            width_std=width_std,
            radius_mean=radius_mean,
            radius_std=radius_std,
            wavelength_mean=wavelength_mean,
            wavelength_std=wavelength_std,
            n_simulations=n_simulations,
            use_ensemble=use_ensemble,
            seed=seed
        )
        
        # Analyze distributions
        thickness_stats = self.analyze_thickness_distribution(results)
        
        if thickness_stats is not None:
            # Create plots
            self.create_distribution_plots(
                results, thickness_stats,
                width_mean, width_std,
                radius_mean, radius_std,
                wavelength_mean, wavelength_std
            )
            
            # Save results
            output_data = {
                'thickness_stats': thickness_stats,
                'simulation_parameters': {
                    'n_simulations': n_simulations,
                    'width_mean': width_mean,
                    'width_std': width_std,
                    'radius_mean': radius_mean,
                    'radius_std': radius_std,
                    'wavelength_mean': wavelength_mean,
                    'wavelength_std': wavelength_std,
                    'model_type': model_type,
                    'use_ensemble': use_ensemble,
                    'seed': seed
                },
                'results': {
                    'thickness_mean': float(thickness_stats['mean']),
                    'thickness_std': float(thickness_stats['std']),
                    'thickness_cv': float(thickness_stats['cv']),
                    'thickness_range': [float(thickness_stats['min']), float(thickness_stats['max'])],
                    'valid_samples': int(results['valid_samples']),
                    'success_rate': float(results['valid_samples']/results['n_simulations']*100)
                }
            }
            
            json_output_file = 'inverse_monte_carlo_results.json'
            with open(json_output_file, 'w') as f:
                json.dump(output_data, f, indent=2)
            
            # Save thickness distribution to .npz file
            npz_output_file = 'inverse_monte_carlo_thickness_distribution.npz'
            np.savez(
                npz_output_file,
                thickness=results['thickness'],
                width_samples=results['width_samples'],
                radius_samples=results['radius_samples'],
                wavelength_samples=results['wavelength_samples'],
                thickness_mean=thickness_stats['mean'],
                thickness_std=thickness_stats['std'],
                thickness_percentiles=np.array([
                    thickness_stats['percentile_5'],
                    thickness_stats['percentile_25'],
                    thickness_stats['percentile_50'],
                    thickness_stats['percentile_75'],
                    thickness_stats['percentile_95']
                ]),
                input_parameters=np.array([
                    width_mean, width_std,
                    radius_mean, radius_std,
                    wavelength_mean, wavelength_std
                ]),
                n_simulations=n_simulations,
                valid_samples=results['valid_samples']
            )
            
            print(f"\n✅ Inverse Monte Carlo uncertainty analysis complete!")
            print(f"📊 Results saved to: {json_output_file}")
            print(f"💾 Thickness distribution saved to: {npz_output_file}")
            
            return results, thickness_stats
        else:
            print(f"\n❌ Analysis failed - no valid thickness predictions!")
            return results, None

def main():
    """Main function to run the inverse Monte Carlo analysis with example parameters."""
    # Create figures directory if it doesn't exist
    Path("figures").mkdir(exist_ok=True)
    
    # Initialize analysis
    analysis = InverseMonteCarloAnalysisV2()
    
    # Run inverse Monte Carlo analysis
    print("🔬 Inverse Monte Carlo Analysis")
    print("-" * 50)
    results1, stats1 = analysis.run_analysis(
        width_mean=0.330,      # Mean width in μm
        width_std=0.004,      # Width uncertainty in μm (±5 nm)
        radius_mean=0.045,     # Mean radius in μm
        radius_std=0.004,     # Radius uncertainty in μm (±3 nm)
        wavelength_mean=633.2,  # Target wavelength in nm
        wavelength_std=9.0,    # Wavelength uncertainty in nm
        n_simulations=10000,
        model_type='linear_interactions',
        use_ensemble=False,
        seed=42
    )
    
    if stats1 is not None:
        print(f"\n🎯 Summary:")
        print(f"  Input: Width {0.330:.3f}±{0.004:.3f} μm, Radius {0.045:.3f}±{0.004:.3f} μm, Wavelength {633.2:.1f}±{9.0:.1f} nm")
        print(f"  Predicted thickness: {stats1['mean']:.3f} ± {stats1['std']:.3f} μm")
        print(f"  Thickness CV: {stats1['cv']:.1f}%")
        print(f"  90% confidence interval: {stats1['percentile_5']:.3f} - {stats1['percentile_95']:.3f} μm")

if __name__ == "__main__":
    main()
